CREATE TABLE VN_WS_CREDENTIALS (

	VENDOR_ID numeric(24,0) NOT NULL,
	USERNAME varchar(25) NOT NULL,
	PASSWORD varchar(255) NOT NULL,
	ISSUE_DATE datetime2(7) NOT NULL DEFAULT (GETDATE()) 

	CONSTRAINT VN_WS_CREDENTIALS_PK PRIMARY KEY (VENDOR_ID),
	CONSTRAINT VN_WS_CREDENTIALS_FORNITORE_FK FOREIGN KEY (VENDOR_ID) REFERENCES FORNITORE(ID_FORNITORE),
) ;

CREATE TABLE WS_ACCESSTOKEN (

	ID bigint IDENTITY(1,1) NOT NULL,
	VENDOR_ID numeric(24,0) NOT NULL,
	TOKEN varchar(255) NOT NULL,
	ISSUE_DATE datetime2(7) NOT NULL DEFAULT (GETDATE()), 
	EXPIRATION_DATE datetime2(7) 

	CONSTRAINT WS_ACCESSTOKEN_PK PRIMARY KEY (ID),
	CONSTRAINT WS_ACCESSTOKEN_VN_WS_CREDENTIALS_FK FOREIGN KEY (VENDOR_ID) REFERENCES VN_WS_CREDENTIALS(VENDOR_ID),
) ;